// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// prisma.config.ts
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { PrismaPg } from "@prisma/adapter-pg";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // remplace le simple "url: ..." par un vrai adapter
  datasource: {
    url: process.env["DATABASE_URL"],
  },
  adapter: async () => {
    return new PrismaPg({ connectionString: process.env["DATABASE_URL"] });
  },
});